library(dplyr)
library(tidyr)
library(purrr)

number_range <- sprintf('%0.2d', 0:99)
# ICD level 2 matching table
ICD2 <- data.frame(
    letter = rep(LETTERS, each = 100),
    number = rep(number_range, length(LETTERS))
)

ICD2_labeled <- ICD2 %>%
    mutate(ICD_level_2 = case_when(
        letter == "A" & number %in% number_range[1:10] ~ "Intestinal infectious diseases",
        letter == "A" & number %in% number_range[16:20] ~ "Tuberculosis",
        letter == "A" & number %in% number_range[21:29] ~ "Certain zoonotic bacterial diseases",
        letter == "A" & number %in% number_range[31:50] ~ "Other bacterial diseases",
        letter == "A" & number %in% number_range[51:65] ~ "Infections with a predominantly sexual mode of transmission",
        letter == "A" & number %in% number_range[66:70] ~ "Other spirochaetal diseases",
        letter == "A" & number %in% number_range[71:75] ~ "Other diseases caused by chlamydiae",
        letter == "A" & number %in% number_range[76:80] ~ "Rickettsioses",
        letter == "A" & number %in% number_range[81:90] ~ "Viral infections of the central nervous system",
        letter == "A" & number %in% number_range[91:100] ~ "Arthropod-borne viral fevers and viral hemorrhagic fevers",
        letter == "B" & number %in% number_range[1:10] ~ "Viral infections characterized by skin and mucous membrane lesions",
        letter == "B" & number %in% number_range[16:20] ~ "Viral hepatitis",
        letter == "B" & number %in% number_range[21:25] ~ "Human immunodeficiency virus [HIV] disease",
        letter == "B" & number %in% number_range[26:35] ~ "Other viral diseases",
        letter == "B" & number %in% number_range[36:50] ~ "Mycoses",
        letter == "B" & number %in% number_range[51:65] ~ "Protozoal diseases",
        letter == "B" & number %in% number_range[66:84] ~ "Helminthiases",
        letter == "B" & number %in% number_range[86:90] ~ "Pediculosis, acariasis and other infestations",
        letter == "B" & number %in% number_range[91:95] ~ "Sequelae of infectious and parasitic diseases",
        letter == "B" & number %in% number_range[96:99] ~ "Bacterial, viral and other infectious agents",
        letter == "B" & number == "99" ~ "Other and unspecified infectious diseases",
        letter == "C" & number %in% number_range[1:98] ~ "Malignant neoplasms",
        letter == "D" & number %in% number_range[1:10] ~ "In situ neoplasms",
        letter == "D" & number %in% number_range[11:37] ~ "Benign neoplasms",
        letter == "D" & number %in% number_range[38:49] ~ "Neoplasms of uncertain or unknown behaviour",
        letter == "D" & number %in% number_range[51:54] ~ "Nutritional anaemias",
        letter == "D" & number %in% number_range[56:60] ~ "Haemolytic anaemias",
        letter == "D" & number %in% number_range[61:65] ~ "Aplastic and other anaemias",
        letter == "D" & number %in% number_range[66:70] ~ "Coagulation defects, purpura and other haemorrhagic conditions",
        letter == "D" & number %in% number_range[71:78] ~ "Other diseases of blood and blood-forming organs",
        letter == "D" & number %in% number_range[81:90] ~ "Certain disorders involving the immune mechanism",
        letter == "E" & number %in% number_range[1:8] ~ "Disorders of thyroid gland",
        letter == "E" & number %in% number_range[11:15] ~ "Diabetes mellitus",
        letter == "E" & number %in% number_range[16:17] ~ "Other disorders of glucose regulation and pancreatic internal secretion",
        letter == "E" & number %in% number_range[21:36] ~ "Disorders of other endocrine glands",
        letter == "E" & number %in% number_range[41:47] ~ "Malnutrition",
        letter == "E" & number %in% number_range[51:65] ~ "Other nutritional deficiencies",
        letter == "E" & number %in% number_range[66:69] ~ "Obesity and other hyperalimentation",
        letter == "E" & number %in% number_range[71:91] ~ "Metabolic disorders",
        letter == "F" & number %in% number_range[1:10] ~ "Organic, including symptomatic, mental disorders",
        letter == "F" & number %in% number_range[11:20] ~ "Mental and behavioural disorders due to psychoactive substance use",
        letter == "F" & number %in% number_range[21:30] ~ "Schizophrenia, schizotypal and delusional disorders",
        letter == "F" & number %in% number_range[31:40] ~ "Mood [affective] disorders",
        letter == "F" & number %in% number_range[41:49] ~ "Neurotic, stress-related and somatoform disorders",
        letter == "F" & number %in% number_range[51:60] ~ "Behavioural syndromes associated with physiological disturbances and physical factors",
        letter == "F" & number %in% number_range[61:70] ~ "Disorders of adult personality and behaviour",
        letter == "F" & number %in% number_range[71:80] ~ "Mental retardation",
        letter == "F" & number %in% number_range[81:90] ~ "Disorders of psychological development",
        letter == "F" & number %in% number_range[91:99] ~ "Behavioural and emotional disorders with onset usually occurring in childhood and adolescence",
        letter == "F" & number == "99" ~ "Mental disorder, not otherwise specified",
        letter == "G" & number %in% number_range[1:10] ~ "Inflammatory diseases of the central nervous system",
        letter == "G" & number %in% number_range[11:14] ~ "Systemic atrophies primarily affecting the central nervous system",
        letter == "G" & number %in% number_range[21:27] ~ "Extrapyramidal and movement disorders",
        letter == "G" & number %in% number_range[31:33] ~ "Other degenerative diseases of the nervous system",
        letter == "G" & number %in% number_range[36:38] ~ "Demyelinating diseases of the central nervous system",
        letter == "G" & number %in% number_range[41:48] ~ "Episodic and paroxysmal disorders",
        letter == "G" & number %in% number_range[51:60] ~ "Nerve, nerve root and plexus disorders",
        letter == "G" & number %in% number_range[61:65] ~ "Polyneuropathies and other disorders of the peripheral nervous system",
        letter == "G" & number %in% number_range[71:74] ~ "Diseases of myoneural junction and muscle",
        letter == "G" & number %in% number_range[81:84] ~ "Cerebral palsy and other paralytic syndromes",
        letter == "G" & number %in% number_range[91:100] ~ "Other disorders of the nervous system",
        letter == "H" & number %in% number_range[1:7] ~ "Disorders of eyelid, lacrimal system and orbit",
        letter == "H" & number %in% number_range[11:14] ~ "Disorders of conjunctiva",
        letter == "H" & number %in% number_range[16:23] ~ "Disorders of sclera, cornea, iris and ciliary body",
        letter == "H" & number %in% number_range[26:29] ~ "Disorders of lens",
        letter == "H" & number %in% number_range[31:37] ~ "Disorders of choroid and retina",
        letter == "H" & number %in% number_range[41:43] ~ "Glaucoma",
        letter == "H" & number %in% number_range[44:46] ~ "Disorders of vitreous body and globe",
        letter == "H" & number %in% number_range[47:49] ~ "Disorders of optic nerve and visual pathways",
        letter == "H" & number %in% number_range[50:53] ~ "Disorders of ocular muscles, binocular movement, accommodation and refraction",
        letter == "H" & number %in% number_range[54:55] ~ "Visual disturbances and blindness",
        letter == "H" & number %in% number_range[56:60] ~ "Other disorders of eye and adnexa",
        letter == "H" & number %in% number_range[61:63] ~ "Diseases of external ear",
        letter == "H" & number %in% number_range[66:76] ~ "Diseases of middle ear and mastoid",
        letter == "H" & number %in% number_range[81:84] ~ "Diseases of inner ear",
        letter == "H" & number %in% number_range[91:96] ~ "Other disorders of ear",
        letter == "I" & number %in% number_range[1:3] ~ "Acute rheumatic fever",
        letter == "I" & number %in% number_range[6:10] ~ "Chronic rheumatic heart diseases",
        letter == "I" & number %in% number_range[11:16] ~ "Hypertensive diseases",
        letter == "I" & number %in% number_range[21:26] ~ "Ischaemic heart diseases",
        letter == "I" & number %in% number_range[27:29] ~ "Pulmonary heart disease and diseases of pulmonary circulation",
        letter == "I" & number %in% number_range[31:53] ~ "Other forms of heart disease",
        letter == "I" & number %in% number_range[61:70] ~ "Cerebrovascular diseases",
        letter == "I" & number %in% number_range[71:80] ~ "Diseases of arteries, arterioles and capillaries",
        letter == "I" & number %in% number_range[81:90] ~ "Diseases of veins, lymphatic vessels and lymph nodes, not elsewhere classified",
        letter == "I" & number %in% number_range[96:100] ~ "Other and unspecified disorders of the circulatory system",
        letter == "J" & number %in% number_range[1:7] ~ "Acute upper respiratory infections",
        letter == "J" & number %in% number_range[10:19] ~ "Influenza and pneumonia",
        letter == "J" & number %in% number_range[21:23] ~ "Other acute lower respiratory infections",
        letter == "J" & number %in% number_range[31:40] ~ "Other diseases of upper respiratory tract",
        letter == "J" & number %in% number_range[41:48] ~ "Chronic lower respiratory diseases",
        letter == "J" & number %in% number_range[61:71] ~ "Lung diseases due to external agents",
        letter == "J" & number %in% number_range[81:85] ~ "Other respiratory diseases principally affecting the interstitium",
        letter == "J" & number %in% number_range[86:87] ~ "Suppurative and necrotic conditions of lower respiratory tract",
        letter == "J" & number %in% number_range[91:95] ~ "Other diseases of pleura",
        letter == "J" & number %in% number_range[96:100] ~ "Other diseases of the respiratory system",
        letter == "K" & number %in% number_range[1:15] ~ "Diseases of oral cavity, salivary glands and jaws",
        letter == "K" & number %in% number_range[21:32] ~ "Diseases of oesophagus, stomach and duodenum",
        letter == "K" & number %in% number_range[36:39] ~ "Diseases of appendix",
        letter == "K" & number %in% number_range[41:47] ~ "Hernia",
        letter == "K" & number %in% number_range[51:53] ~ "Noninfective enteritis and colitis",
        letter == "K" & number %in% number_range[56:64] ~ "Other diseases of intestines",
        letter == "K" & number %in% number_range[66:68] ~ "Diseases of peritoneum",
        letter == "K" & number %in% number_range[71:78] ~ "Diseases of liver",
        letter == "K" & number %in% number_range[81:88] ~ "Disorders of gallbladder, biliary tract and pancreas",
        letter == "K" & number %in% number_range[91:94] ~ "Other diseases of the digestive system",
        letter == "L" & number %in% number_range[1:9] ~ "Infections of the skin and subcutaenous tissue",
        letter == "L" & number %in% number_range[11:15] ~ "Bullous disorders",
        letter == "L" & number %in% number_range[21:31] ~ "Dermatitis and eczema",
        letter == "L" & number %in% number_range[41:46] ~ "Papulosquamous disorders",
        letter == "L" & number %in% number_range[51:55] ~ "Urticaria and erythema",
        letter == "L" & number %in% number_range[56:60] ~ "Radiation-related disorders of the skin and subcutaneous tissue",
        letter == "L" & number %in% number_range[61:76] ~ "Disorders of skin appendages",
        letter == "L" & number %in% number_range[81:100] ~ "Other disorders of the skin and subcutaneous tissue",
        letter == "M" & number %in% number_range[1:26] ~ "Arthropathies",
        letter == "M" & number %in% number_range[31:37] ~ "Systemic connective tissue disorders",
        letter == "M" & number %in% number_range[41:55] ~ "Dorsopathies",
        letter == "M" & number %in% number_range[61:80] ~ "Soft tissue disorders",
        letter == "M" & number %in% number_range[81:95] ~ "Osteopathies and chondropathies",
        letter == "M" & number %in% number_range[96:100] ~ "Other disorders of the musculoskeletal system and connective tissue",
        letter == "N" & number %in% number_range[1:9] ~ "Glomerular diseases",
        letter == "N" & number %in% number_range[11:17] ~ "Renal tubulo-interstitial diseases",
        letter == "N" & number %in% number_range[18:20] ~ "Renal failure",
        letter == "N" & number %in% number_range[21:24] ~ "Urolithiasis",
        letter == "N" & number %in% number_range[26:30] ~ "Other disorders of kidney and ureter",
        letter == "N" & number %in% number_range[31:40] ~ "Other diseases of urinary system",
        letter == "N" & number %in% number_range[41:52] ~ "Diseases of male genital organs",
        letter == "N" & number %in% number_range[61:65] ~ "Disorders of breast",
        letter == "N" & number %in% number_range[71:78] ~ "Inflammatory diseases of female pelvic organs",
        letter == "N" & number %in% number_range[81:99] ~ "Noninflammatory disorders of female genital tract",
        letter == "N" & number == "99" ~ "Postprocedural disorders of genitourinary system, not elsewhere classified",
        letter == "O" & number %in% number_range[1:9] ~ "Pregnancy with abortive outcome",
        letter == "O" & number %in% number_range[11:17] ~ "Oedema, proteinuria and hypertensive disorders in pregnancy, childbirth and the puerperium",
        letter == "O" & number %in% number_range[21:30] ~ "Other maternal disorders predominantly related to pregnancy",
        letter == "O" & number %in% number_range[31:49] ~ "Maternal care related to the fetus and amniotic cavity and possible delivery problems",
        letter == "O" & number %in% number_range[61:76] ~ "Complications of labour and delivery",
        letter == "O" & number %in% number_range[81:85] ~ "Delivery",
        letter == "O" & number %in% number_range[86:93] ~ "Complications predominantly related to the puerperium",
        letter == "O" & number %in% number_range[95:100] ~ "Other obstetric conditions, not elsewhere classified",
        letter == "P" & number %in% number_range[1:5] ~ "Fetus and newborn affected by maternal factors and by complications of pregnancy, labour and delivery",
        letter == "P" & number %in% number_range[6:9] ~ "Disorders related to length of gestation and fetal growth",
        letter == "P" & number %in% number_range[11:16] ~ "Birth trauma",
        letter == "P" & number %in% number_range[21:30] ~ "Respiratory and cardiovascular disorders specific to the perinatal period",
        letter == "P" & number %in% number_range[36:40] ~ "Infections specific to the perinatal period",
        letter == "P" & number %in% number_range[51:62] ~ "Haemorrhagic and haematological disorders of fetus and newborn",
        letter == "P" & number %in% number_range[71:75] ~ "Transitory endocrine and metabolic disorders specific to fetus and newborn",
        letter == "P" & number %in% number_range[76:79] ~ "Digestive system disorders of fetus and newborn",
        letter == "P" & number %in% number_range[81:84] ~ "Conditions involving the integument and temperature regulation of fetus and newborn",
        letter == "P" & number %in% number_range[91:97] ~ "Other disorders originating in the perinatal period",
        letter == "Q" & number %in% number_range[1:8] ~ "Congenital malformations of the nervous system",
        letter == "Q" & number %in% number_range[11:19] ~ "Congenital malformations of eye, ear, face and neck",
        letter == "Q" & number %in% number_range[21:29] ~ "Congenital malformations of the circulatory system",
        letter == "Q" & number %in% number_range[31:35] ~ "Congenital malformations of the respiratory system",
        letter == "Q" & number %in% number_range[36:38] ~ "Cleft lip and cleft palate",
        letter == "Q" & number %in% number_range[39:46] ~ "Other congenital malformations of the digestive system",
        letter == "Q" & number %in% number_range[51:57] ~ "Congenital malformations of genital organs",
        letter == "Q" & number %in% number_range[61:65] ~ "Congenital malformations of the urinary system",
        letter == "Q" & number %in% number_range[66:80] ~ "Congenital malformations and deformations of the musculoskeletal system",
        letter == "Q" & number %in% number_range[81:90] ~ "Other congenital malformations",
        letter == "Q" & number %in% number_range[91:100] ~ "Chromosomal abnormalities, not elsewhere classified",
        letter == "R" & number %in% number_range[1:10] ~ "Symptoms and signs involving the circulatory and respiratory systems",
        letter == "R" & number %in% number_range[11:20] ~ "Symptoms and signs involving the digestive system and abdomen",
        letter == "R" & number %in% number_range[21:24] ~ "Symptoms and signs involving the skin and subcutaneous tissue",
        letter == "R" & number %in% number_range[26:30] ~ "Symptoms and signs involving the nervous and musculoskeletal systems",
        letter == "R" & number %in% number_range[31:40] ~ "Symptoms and signs involving the urinary system",
        letter == "R" & number %in% number_range[41:47] ~ "Symptoms and signs involving cognition, perception, emotional state and behaviour",
        letter == "R" & number %in% number_range[48:50] ~ "Symptoms and signs involving speech and voice",
        letter == "R" & number %in% number_range[51:70] ~ "General symptoms and signs",
        letter == "R" & number %in% number_range[71:80] ~ "Abnormal findings on examination of blood, without diagnosis",
        letter == "R" & number %in% number_range[81:83] ~ "Abnormal findings on examination of urine, without diagnosis",
        letter == "R" & number %in% number_range[84:90] ~ "Abnormal findings on examination of other body fluids, substances and tissues, without diagnosis",
        letter == "R" & number %in% number_range[91:95] ~ "Abnormal findings on diagnostic imaging and in function studies, without diagnosis",
        letter == "R" & number %in% number_range[96:100] ~ "Ill-defined and unknown causes of mortality",
        letter == "S" & number %in% number_range[1:10] ~ "Injuries to the head",
        letter == "S" & number %in% number_range[11:20] ~ "Injuries to the neck",
        letter == "S" & number %in% number_range[21:30] ~ "Injuries to the thorax",
        letter == "S" & number %in% number_range[31:40] ~ "Injuries to the abdomen, lower back, lumbar spine and pelvis",
        letter == "S" & number %in% number_range[41:50] ~ "Injuries to the shoulder and upper arm",
        letter == "S" & number %in% number_range[51:60] ~ "Injuries to the elbow and forearm",
        letter == "S" & number %in% number_range[61:70] ~ "Injuries to the wrist and hand",
        letter == "S" & number %in% number_range[71:80] ~ "Injuries to the hip and thigh",
        letter == "S" & number %in% number_range[81:90] ~ "Injuries to the knee and lower leg",
        letter == "S" & number %in% number_range[91:100] ~ "Injuries to the ankle and foot",
        letter == "T" & number %in% number_range[1:8] ~ "Injuries involving multiple body regions",
        letter == "T" & number %in% number_range[9:15] ~ "Injuries to unspecified part of trunk, limb or body region",
        letter == "T" & number %in% number_range[16:20] ~ "Effects of foreign body entering through natural orifice",
        letter == "T" & number %in% number_range[21:33] ~ "Burns and corrosions",
        letter == "T" & number %in% number_range[34:36] ~ "Frostbite",
        letter == "T" & number %in% number_range[37:51] ~ "Poisoning by drugs, medicaments and biological substances",
        letter == "T" & number %in% number_range[52:66] ~ "Toxic effects of substances chiefly nonmedicinal as to source",
        letter == "T" & number %in% number_range[67:79] ~ "Other and unspecified effects of external causes",
        letter == "T" & number == "79" ~ "Certain early complications of trauma, not elsewhere classified",
        letter == "T" & number %in% number_range[81:89] ~ "Complications of surgical and medical care, not elsewhere classified",
        letter == "T" & number %in% number_range[91:99] ~ "Sequelae of injuries, of poisoning and of other consequences of external causes",
        letter == "U" & number %in% number_range[1:50] ~ "Provisional assignment of new diseases of uncertain etiology",
        letter == "U" & number %in% number_range[81:90] ~ "Bacterial agents resistant to antibiotics",
        letter == "V" & number == "00" ~ "Pedestrian conveyance accident",
        letter %in% c("V", "X") & number %in% number_range[2:60] ~ "Accidents",
        letter == "X" & number %in% number_range[61:85] ~ "Suicide or other intentional self-harm",
        letter == "X" & number %in% number_range[86:100] ~ "Assault",
        letter == "Y" & number %in% number_range[1:10] ~ "Assault",
        letter == "Y" & number %in% number_range[11:35] ~ "Injuring events of undetermined intent",
        letter == "Y" & number %in% number_range[36:37] ~ "Legal intervention and operations of war",
        letter == "Y" & number %in% number_range[41:85] ~ "Complications in medical care",
        letter == "Y" & number %in% number_range[86:90] ~ "Sequelae of external causes of morbidity and mortality",
        letter == "Y" & number %in% number_range[91:99] ~ "Supplementary factors related to causes of morbidity and mortality classified elsewhere",
        letter == "Z" & !(number %in% number_range) ~ "Localization code",
        letter == "Z" & number %in% number_range[1:14] ~ "Persons encountering health services for examination and investigation",
        letter == "Z" & number %in% number_range[21:30] ~ "Persons with potential health hazards related to communicable diseases",
        letter == "Z" & number %in% number_range[31:40] ~ "Persons encountering health services in circumstances related to reproduction",
        letter == "Z" & number %in% number_range[41:55] ~ "Persons encountering health services for specific procedures and health care",
        letter == "Z" & number %in% number_range[56:66] ~ "Persons with potential health hazards related to socioeconomic and psychosocial circumstances",
        letter == "Z" & number %in% number_range[71:77] ~ "Persons encountering health services in other circumstances",
        letter == "Z" & number %in% number_range[81:100] ~ "Persons with potential health hazards related to family and personal history and certain conditions influencing health status",
        TRUE ~ NA
))